apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: nodejs-app=9421-1477-0456.dkr.ecr.eu-central-1.amazonaws.com/nodejs-app
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: node-js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: ahmedabo3lii/devops-capstone_app:v1
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "mysecretpassword"
        - name: DB_NAME
          value: "nodejs_app"
        - name: DB_PORT
          value: "3306"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default
spec:
  selector:
    app: nodejs-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP