apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nodejs.yaml
  - mysql.yaml
  - redis.yaml

  # - ../../k8s/nodejs.yaml
  # - ../../k8s/mysql.yaml
  # - ../../k8s/redis.yaml